title: "Matthew Mettler"
description: ""
theme: minima

url: "https://matthewmettler.github.io"

# Optional: add real links or leave empty for now
minima:
  social_links: []

header_pages:
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
