title: "Matthew Mettler"
description: "Political Science, University of Illinois Urbana Champaign"
theme: minima

url: "https://matthewmettler.github.io"

minima:
  social_links: []

header_pages:
  - research.md
  - publications.md
  - teaching.md
  - cv.md
